services:
  - type: web
    name: word-processor-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: mi-clave-super-secreta-para-produccion-2025
      - key: PORT
        value: 10000
